/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StyleSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var PADDING_MAP = { 1: 23, 2: 40, 3: 56, 4: 73 };
function getPadding(level) {
  var _a;
  return (_a = PADDING_MAP[level]) != null ? _a : 6 + level * 17;
}
var LIST_RE = /^(\s*)([-*+]|\d+[.)])\s/;
var INDENT_SIZE = 4;
function getListLevel(lineText) {
  var _a, _b;
  const m = lineText.match(LIST_RE);
  if (!m) return 0;
  const indent = (_b = (_a = m[1]) == null ? void 0 : _a.length) != null ? _b : 0;
  return Math.floor(indent / INDENT_SIZE) + 1;
}
function isEmpty(lineText) {
  return lineText.trim() === "";
}
function buildDecorations(view) {
  const builder = new import_state.RangeSetBuilder();
  const doc = view.state.doc;
  let activePadding = 0;
  for (let i = 1; i <= doc.lines; i++) {
    const line = doc.line(i);
    const text = line.text;
    const level = getListLevel(text);
    if (level > 0) {
      activePadding = getPadding(level);
      continue;
    }
    if (activePadding > 0) {
      if (isEmpty(text)) {
        builder.add(
          line.from,
          line.from,
          import_view.Decoration.line({ attributes: { style: `padding-inline-start: ${activePadding}px` } })
        );
        activePadding = 0;
        continue;
      }
      builder.add(
        line.from,
        line.from,
        import_view.Decoration.line({ attributes: { style: `padding-inline-start: ${activePadding}px` } })
      );
      continue;
    }
  }
  return builder.finish();
}
var listIndentPlugin = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged) {
        this.decorations = buildDecorations(update.view);
      }
    }
  },
  { decorations: (v) => v.decorations }
);
var StyleSyncPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerEditorExtension([listIndentPlugin]);
  }
  onunload() {
  }
};
